#!/bin/bash

rm -rf *.zip
rm -rf flashable/zip/system
mkdir flashable/zip/system/ && mkdir flashable/zip/system/lib/ && mkdir flashable/zip/system/lib/modules/
cd flashable/zip/kernel/
rm -rf zImage
cd ../../..

if [ ! -f arch/arm/boot/zImage ];
then
    echo An error occured in the build process, aborting...
        exit 1
fi
echo Copying files and making flashable
cp -f arch/arm/boot/zImage flashable/zip/kernel/zImage
find -iname "*.ko" -exec cp {} flashable/zip/system/lib/modules/ \; >/dev/null
cd flashable/zip/
zip -r9 ../../ds-kernel.zip *
cd ../..
java -jar flashable/tools/signapk.jar flashable/tools/testkey.x509.pem flashable/tools/testkey.pk8 ds-kernel.zip ds-kernel_signed.zip
rm -rf ds-kernel.zip
echo done
